# Workflow to Build the nodejs code
---
name:  Build the nodejs code
on: push
jobs:
    Build-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v7
            with:
                repository: Sonal0409/GithubActions-NodeJs-Demo
                ref: master 
          - name: Install Nodejs
            uses: actions/setup-node@v7
            with:
                node-version: '18'
          - name: Install dependencies
            run: npm ci
          - name: Execute the test cases
            run: npm test
          - name: Build the application
            run: npm run build