# Sonarqube integration with github actions
---
name: Sonarqube integration
on: workflow_dispatch

jobs:
  Checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v7
        with:
          repository: allius01/SonarQubeCoverageJava
          ref: master

      - name: Install java and maven
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.2.0.4988
            -Dsonar.projectKey=org-lmt_CI-with-githubActions
            -Dsonar.organization=org-lmt
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
